version: '3.8'

services:
  framework:
    build:
      context: ./framework
    ports:
      - "5000:5000"
    environment:
      - LLM_URL=http://llm:5001

  llm:
    build:
      context: ./llm
    ports:
      - "5001:5001"
