apiVersion: apps/v1
kind: Deployment
metadata:
  name: framework-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: framework
  template:
    metadata:
      labels:
        app: framework
    spec:
      containers:
        - name: framework
          image: lausiv/framework:latest
          ports:
            - containerPort: 5000
          env:
            - name: LLM_URL
              value: "http://llm-service:5001"
---
apiVersion: v1
kind: Service
metadata:
  name: framework-service
spec:
  type: NodePort  # NodePort 타입으로 변경
  selector:
    app: framework
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000  # 노드 포트 번호 지정 (30000-32767 사이)
